site_name: ERP – openLCA Synchronisation Kit

theme:
  name: material
  color_mode: auto

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Adoption View:
      - Introduction: adoption-view/introduction.md
      - Use Case: adoption-view/use-case.md
      - Customer Journey: adoption-view/customer-journey.md
      - Semantic Models: adoption-view/semantic-models.md
      - Additional Resources: adoption-view/additional-resources.md
  - Development View:
      - Architecture Overview: development-view/architecture-overview.md
      - Data Retrieval Flow: development-view/data-retrieval-flow.md
  - Operation View:
      - Configuration Guide: operation-view/configuration-guide.md

